### ISSUE TITLE
Web URL compatibility

### ISSUE THREAD

**Issue by ghost** [jkramr/latynka#10]
Just a boring think for the web developer who make transliteration following to this case just #8

I know that web standards are changing, a question of time, but urlencode still return me abracadabra with extra chars yet.

Just a subject to think about ;)

Best regards!

**Comment by jkramr** [comment]
Not sure what you mean by that. I'm not a web/frontend developer. Is it related to this particular npm library?
The library does use Ukrainian cyrillic letters, and I've seen abracadabra issues when using browserify to flatten the js script for web interface. I'm guessing that it does have everything to do with cyrillic symbols/unicode support of a framework you're trying to use. But again, I didn't quite get the context in which you're getting the issue.
