### ISSUE TITLE
Alternative keyboard layout

### ISSUE THREAD

**Issue by the-forgotten-hero** [jkramr/latynka#12]
I found this keyboard layout conception more useful, at least for developers. 
It is the standard US / QWERTY layout, that extended by using Alt Gr keys on same chars.

For example
```
š = altgr + s
č = altgr + c
ž = altgr + z
ĝ = altgr + g
```
And example of keymap file

```
//
// cp /usr/share/X11/xkb/symbols/ukr-latynka-org-altgr
// setxkbmap -layout ukr-latynka-org-altgr
// ===
//
partial alphanumeric_keys
xkb_symbols "ukr-latynka-org-altgr" {
  include "us(basic)"
  name[Group1]= "Ukrainian (Alt Gr / ukr-latynka.org)";

    key <AB01> {  [z, Z, zcaron, Zcaron] };
    key <AB03> {  [c, C, ccaron, Ccaron] };
    key <AC02> {  [s, S, scaron, Scaron] };
    key <AC05> {  [g, G, gcircumflex, Gcircumflex] };
};
```

Anyway here is the original conception by it author, implemented as the exemple for linux / X11 users
https://github.com/jkramr/latynka/pull/11 not sure about the special chars just, me using my own version above as more plain for myself.

**Comment by witchmonster** [comment]
Thank you for this layout! It's been a while since I worked in Linux. Used to be my native OS for 15 years before I got corrupted by corporate Macs :). Good stuff. Merged your PR: https://github.com/jkramr/latynka/pull/11
