### ISSUE TITLE
Конструкція "ьо"

### ISSUE THREAD

**Issue by Dead-TR** [jkramr/latynka#13]
В конструкції, це вживається "мякий знак - о" ("ьо"), латинкою замість апострофа з'являється буква "j"

На приклад:
"Цьому" => "Cjomu"
А це вже виходить слово не "цьому", а "цйому".

**Comment by Dead-TR** [comment]
![Screenshot_2023-04-06-18-20-35-176_com android chrome](https://user-images.githubusercontent.com/63505873/230424446-0c1a6c18-4f14-4b59-bd83-785a4efd7c52.jpg)

**Comment by witchmonster** [comment]
ce ne pomylka, ce te, jak pracjuje dana abetka, perečytajte pravyla ta FAQ, bud' laska
