### ISSUE TITLE
Не працює кнопка «копіювати»

### ISSUE THREAD

**Issue by kapuchinokava** [jkramr/latynka#2]
Коли натискаю на кнопку «копіювати» текст, написаний латинкою не копіюється

**Comment by jkramr** [comment]
Дякую! Цей баг стосується до веб-проєкту, а не до самого алгоритму латинки, тому закриваю його тут.
Перевідкрила його у відповідному репозиторії. Перейдіть, будь ласка, за покликанням https://github.com/jkramr/latynka-web/issues/10 і прокоментуйте який броузер використовуєте. В Chrome (десктоп і мобайл) і Firefox відтворити у мене не вийшло.
