### ISSUE TITLE
йогурт

### ISSUE THREAD

**Issue by Usland123** [jkramr/latynka#3]
додати слово йогурт до винятків
![Знімок екрана з 2023-01-03 16-33-15](https://user-images.githubusercontent.com/72984028/210389549-bbaf4379-9818-413d-9400-a28f76df618e.png)

**Comment by jkramr** [comment]
djakuju! v ostannih versijah vže maje pracjuvaty

![image](https://user-images.githubusercontent.com/1822434/211209189-34d6b59c-918c-4f80-86c8-602da4e8992f.png)
