### ISSUE TITLE
Alphabet specification in the readme file / website

### ISSUE THREAD

**Issue by the-forgotten-hero** [jkramr/latynka#9]
I found transliteration rules in the app sources, but assured we need to have specified document, it version revisions, human readeble, presented on the main pages as the basics for regular people, not coders.

Wondering, did not found that on the main page.

**Comment by jkramr** [comment]
There's a link to a video describing the alphabet and there's more on it in the FAQ in README.MD, written by Maksym Prudeus. That's exactly the same as the one used in the pinned message of a chat where people learn this alphabet and learn to type using it on different devices so you might want to check those out.

Besides that, entire team including Maxym Proudeus is working on a website resource, that is currently hosted at https://ukr-latynka.org/ (texts and content is under construction, so it's temporarily a fork of my latynka-web simplified interface with no much more info). Everyone is working on it in their own free time and capacity, so I can't give you any time commitments. As far as this repo is concerned, once they are done, I can add a link to the resource in README.MD. I'm only the provider of the underlying algorithm library and a >>>temporary<<< web interface. I don't have a capacity (or expertise, I'm not a frontend developer) to commit to more than that.

Closing this issue as it's not related to this particular repo.
The repo that you're looking for is: https://github.com/ukr-latynka/website
